Clean output to enable use in scripts

diff --git a/usr/bin/lpssh b/usr/bin/lpssh
--- a/usr/bin/lpssh
+++ b/usr/bin/lpssh
@@ -3,9 +3,17 @@
 unset SSH_AUTH_SOCK
 unset SSH_AGENT_PID
 cleanup() {
-  rm -f $TMP
+  if [ -n "$TMP" ]; then
+    rm -f $TMP
+  fi
   if [ -n "$SSH_AGENT_PID" ]; then
-    eval $(ssh-agent -k)
+    if [ -z "$IOTMP" ]; then
+      IOTMP=$(mktemp)
+    fi
+    eval $(ssh-agent -k) > $IOTMP
+  fi
+  if [ -n "$IOTMP" ]; then
+    rm -f $IOTMP
   fi
 }
 trap cleanup EXIT
@@ -16,6 +24,7 @@ if  [ "$1" = "-k" ]; then
   shift
 else
   TMP=$(mktemp)
+  IOTMP=$(mktemp)
   if ! lpass show --notes my-ssh-mappings > $TMP; then
     echo "Failed to get mappings"
     exit 1
@@ -26,6 +35,14 @@ else
   fi
   KEY_NAME=$(egrep "^$1:" $TMP | cut -d: -f2-)
 fi
-eval "$(ssh-agent)"
-lpass show --notes $KEY_NAME | ssh-add -
+if  ! eval "$(ssh-agent)" > $IOTMP; then
+  echo "Failed to start ssh agent"
+  cat $IOTMP
+  exit 1
+fi
+if ! lpass show --notes $KEY_NAME | ssh-add - > $IOTMP 2>&1; then
+  echo "Failed to add key"
+  cat $IOTMP
+  exit 1
+fi
 ssh "$@"
